services:
  - type: worker
    name: tg-bot
    env: python
    plan: hobby
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
    envVars:
      - key: TG_TOKEN
        sync: false