services:
  - type: worker
    name: tg-bot
    env: python
    plan: hobby
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
    envVars:
      - key: TG_TOKEN
        sync: false