services:
  - type: web
    name: tg-bot
    env: python
    plan: hobby
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true